--- 
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-ume-com-br
  namespace: istio-ingress
spec:
  secretName: local-ume-com-br
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - ume
  commonName: local.example.com.br
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - local.example.com.br
    - www.local.example.com.br
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
--- 
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-internal-ume-com-br
  namespace: istio-ingress
spec:
  secretName: local-internal-ume-com-br
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - ume
  commonName: local.internal.example.com.br
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - local.internal.example.com.br
    - www.local.internal.example.com.br
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
