---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: local-ume-com-br-gateway
  namespace: istio-ingress
spec:
  selector:
    istio: ingressgateway # use istio default ingress gateway
  servers:
    - hosts:
        - 'local.example.com.br'
      port:
        name: http
        number: 80
        protocol: HTTP
      tls:
        httpsRedirect: true
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: local-ume-com-br # must be the same as secret that is on istio-ingress ns
      hosts:
        - local.example.com.br