apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app1
        image: [sua imagem]
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config-volume
          mountPath: /mnt/config
      volumes:
      - name: config-volume
        configMap:
          name: app1-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app1-config
data:
  config.yaml: |
    [seu arquivo de configuração]
