apiVersion: v1
kind: Service
metadata:
  name: app-1
spec:
  selector:
    app: app-1
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  - name: internal
    port: 8081
    targetPort: 8080

apiVersion: v1
kind: Service
metadata:
  name: app-2
spec:
  selector:
    app: app-2
  ports:
    - name: http
      port: 9090
      targetPort: 9090
