name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build_app1:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      	with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build and Test App1
      run: |
        cd app-1/main
        go build -o app1
        go test ./...
        cd ../..

    - name: Build Docker Image and Push to Registry
      run: |
        cd app-1
        docker build -t nerocrescend/app-1:$GITHUB_SHA .
        docker push nerocrescend/app-1:$GITHUB_SHA
        cd ..

  build_app2:
    runs-on: ubuntu-latest
    steps:
		- name: Login to Docker Hub
   	  uses: docker/login-action@v2
      	with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}
		
		- name: Checkout
      uses: actions/checkout@v2
		
		
    - name: Build and Test App2
      run: |
        cd app-2/main
        go build -o app2
        go test ./...
        cd ../..
        
    - name: Build Docker Image and Push to Registry
      run: |
        cd app-2
        docker build -t nerocrescend/app-2:$GITHUB_SHA .
        docker push nerocrescend/app-2:$GITHUB_SHA
        cd ..
