name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build_app1:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build and Test App1
      run: |
        go build -o app-1/main
        go test ./app-1/main

    - name: Build Docker Image and Push to Registry
      run: |
        docker build -t nerocrescend/app-1:$GITHUB_SHA .
        docker push nerocrescend/app-1:$GITHUB_SHA

  build_app2:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build and Test App2
      run: |
        go build -o app-2/main
        go test ./app-2/main

    - name: Build Docker Image and Push to Registry
      run: |
        docker build -t nerocrescend/app-2:$GITHUB_SHA .
        docker push nerocrescend/app-2:$GITHUB_SHA
